#pragma once
#include <mfidl.h>
#include <ks.h>
#include <ksproxy.h>
#include <Mferror.h>
#include <mfapi.h>

class CBasePin :
	public IMFAttributes,
	public IKsControl
{
public:
	// IUnknown
	STDMETHODIMP QueryInterface(REFIID, VOID**);
	STDMETHODIMP_(ULONG) AddRef();
	STDMETHODIMP_(ULONG) Release();

	// IKsControl
	STDMETHOD(KsEvent)(PKSEVENT, ULONG, LPVOID, ULONG, ULONG*);
	STDMETHOD(KsMethod)(PKSMETHOD, ULONG, LPVOID, ULONG, ULONG*);
	STDMETHOD(KsProperty)(PKSPROPERTY, ULONG, LPVOID, ULONG, ULONG*);

	// IMFAttributes
	STDMETHOD(Compare)(IMFAttributes*, MF_ATTRIBUTES_MATCH_TYPE, BOOL*);
	STDMETHOD(CompareItem)(REFGUID, REFPROPVARIANT, BOOL*);
	STDMETHOD(CopyAllItems)(IMFAttributes*);
	STDMETHOD(DeleteAllItems)();
	STDMETHOD(DeleteItem)(REFGUID);
	STDMETHOD(GetAllocatedBlob)(REFGUID, UINT8**, UINT32*);
	STDMETHOD(GetAllocatedString)(REFGUID, LPWSTR*, UINT32*);
	STDMETHOD(GetBlob)(REFGUID, UINT8*, UINT32, UINT32*);
	STDMETHOD(GetBlobSize)(REFGUID, UINT32*);
	STDMETHOD(GetCount)(UINT32*);
	STDMETHOD(GetDouble)(REFGUID, double*);
	STDMETHOD(GetGUID)(REFGUID, GUID*);
	STDMETHOD(GetItem)(REFGUID, PROPVARIANT*);
	STDMETHOD(GetItemByIndex)(UINT32, GUID*, PROPVARIANT*);
	STDMETHOD(GetItemType)(REFGUID, MF_ATTRIBUTE_TYPE*);
	STDMETHOD(GetString)(REFGUID, LPWSTR, UINT32, UINT32*);
	STDMETHOD(GetStringLength)(REFGUID, UINT32*);
	STDMETHOD(GetUINT32)(REFGUID, UINT32*);
	STDMETHOD(GetUINT64)(REFGUID, UINT64*);
	STDMETHOD(GetUnknown)(REFGUID, REFIID, LPVOID*);
	STDMETHOD(LockStore)();
	STDMETHOD(SetBlob)(REFGUID, const UINT8*, UINT32);
	STDMETHOD(SetDouble)(REFGUID, double);
	STDMETHOD(SetGUID)(REFGUID, REFGUID);
	STDMETHOD(SetItem)(REFGUID ,REFPROPVARIANT);
	STDMETHOD(SetString)(REFGUID, LPCWSTR);
	STDMETHOD(SetUINT32)(REFGUID, UINT32);
	STDMETHOD(SetUINT64)(REFGUID, UINT64);
	STDMETHOD(SetUnknown)(REFGUID, IUnknown*);
	STDMETHOD(UnlockStore)();

private:
	ULONG m_cRef;
};
